### ISSUE TITLE
Feature request: Helpers in store

### ISSUE THREAD

**Issue by reflog** [catberry/catberry-handlebars#6]
Since Store contains all the data used by the template, it would make sense to include all the functions returned in load() as helpers for that specific template.
I'm not sure if this is a good idea, but I was wondering on what's the best approach to 'scope' the helpers, instead of keeping a global collection.

What do you think?

**Comment by rdner** [comment]
I'm not sure if I've got the idea. Could you please write a small code snippet to demonstrate the feature?

**Comment by reflog** [comment]
Here's the idea of implementing 'test' helper (copy of 'if' helper):

```
class SomeStore {
  load(){
   return {
     someValue: 1,
     test:function(conditional, options) {
        if (isFunction(conditional)) { conditional = conditional.call(this);}
        if ((!options.hash.includeZero && !conditional) || isEmpty(conditional)) {
          return options.inverse(this);
        } else {
          return options.fn(this);
        }
      }    
    };
  }
}
```

template:

```
<div class="entry">
  {{#test someValue}}
    <h1>{{someValue}}</h1>
  {{/test}}
</div>
```

basically - expose all plain values as template context, and all functions as helpers

**Comment by rdner** [comment]
AFAIK, the template engine does not support local helpers, only the global set of helpers you register across all templates.

But I really like the idea, would be convenient to have it.

Do you have an idea hot we can implement that? Also, PR is welcome of course.

**Comment by reflog** [comment]
I was thinking of prefixing the helper with Store name and stripping the
name before template compilation. This way we can have some sort of
namespacing and localize the helpers. It would improve the code
significantly. I'll take a look, see if I have manage to do it.

**Comment by rdner** [comment]
It's been awhile since you proposed the feature, now I've realized what exactly seemed not that good to me. I would avoid any connection between a store and template because stores are the data layer in the framework they should not be aware of any rendering stuff. Well, in case of going further with the feature we need to manage to implement that in the view layer which is "components".

**Comment by reflog** [comment]
Ok :+1:
